version: "3.2"

services:
    eudaqv1-ubuntu:
        build: .
        image: duartej/eudaqv1-ubuntu:eutelescope
    
    runControl:
        image: duartej/eudaqv1-ubuntu:eutelescope
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=unix${DISPLAY}
        depends_on:
            - "eudaqv1-ubuntu"
        networks:
            static_network:
                ipv4_address: 172.20.128.2
        entrypoint: 
            - initialize_service.sh
            - runControl
    
    logger:
        image: duartej/eudaqv1-ubuntu:eutelescope
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: @LOGSDIR
              target: /logs
        environment:
            - DISPLAY=unix${DISPLAY}
        depends_on:
            - "runControl"
        networks:
            static_network:
                ipv4_address: 172.20.128.3
        entrypoint: 
            - initialize_service.sh
            - logger

    dataCollector:
        image: duartej/eudaqv1-ubuntu:eutelescope
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: @DATADIR
              target: /data
        environment:
            - DISPLAY=unix${DISPLAY}
        depends_on:
            - "runControl"
            - "logger"
        networks:
            static_network:
                ipv4_address: 172.20.128.4
        entrypoint: 
            - initialize_service.sh
            - dataCollector

    onlineMon:
        image: duartej/eudaqv1-ubuntu:eutelescope
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: @DATADIR
              target: /data
        environment:
            - DISPLAY=unix${DISPLAY}
        depends_on:
            - "runControl"
            - "logger"
        networks:
            static_network:
                ipv4_address: 172.20.128.5
        entrypoint: 
            - initialize_service.sh
            - onlineMon

networks:
    static_network:
        ipam:
            config:
                - subnet: 172.20.0.0/16
