version: "3.2"

services:
    devcode:
        image: duartej/eudaqv1-ubuntu:eutelescope
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: @CODEDIR
              target: /eudaq/eudaq
        environment:
            - DISPLAY=unix${DISPLAY}
        networks:
            static_network:
                ipv4_address: 172.20.128.20
    
    runControl:
        volumes:
            - type: bind
              source: @CODEDIR
              target: /eudaq/eudaq
    
    logger:
        volumes:
            - type: bind
              source: @CODEDIR
              target: /eudaq/eudaq

    dataCollector:
        volumes:
            - type: bind
              source: @CODEDIR
              target: /eudaq/eudaq
    onlineMon:
        volumes:
            - type: bind
              source: @CODEDIR
              target: /eudaq/eudaq
    
    TestProducer:
        image: duartej/eudaqv1-ubuntu:eutelescope
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: @CODEDIR
              target: /eudaq/eudaq
        environment:
            - DISPLAY=unix${DISPLAY}
        depends_on:
            - "runControl"
            - "logger"
        networks:
            static_network:
                ipv4_address: 172.20.128.6
        entrypoint: 
            - initialize_service.sh
            - TestProducer

